version: '3.4'
services:
  http-interface:
    build: ./src/http_interface
    image: http-interface
    environment: &env 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
      - PUBNUB_SUBSCRIBE_KEY=sub-c-78806dd4-42a6-11e4-aed8-02ee2ddab7fe
      - PUBNUB_CHANNEL=pubnub-twitter
      - FLOWER_PORT=8888
    depends_on:
      - rabbitmq
    restart: 'no'
    ports:
      - "80:5000"
  stream-input:
    build: ./src/stream_input
    image: stream-input
    command: [celery, worker, --app=stream.app, --concurrency=1, --loglevel=INFO, -Q, 'stream_queue']
    environment: *env
    depends_on:
      - rabbitmq
    restart: 'no'
  message-location:
    build: ./src/message_location
    image: message-location
    command: [celery, worker, --app=message_location.app, --concurrency=5, --loglevel=INFO, -Q, 'message_location_queue']
    environment: *env
    depends_on:
      - rabbitmq
    restart: 'no'
  rabbitmq:
    image: rabbitmq:3.8.0
  flower:
    image: mher/flower
    environment: *env
    ports:
      - 8888:8888