version: '3.4'
services:
  celery:
    build: ./src/http_interface
    image: http-interface
    environment: &env 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
     - ./src/http_interface/:/app
    ports:
      - "80:5000"
  rabbitmq:
    image: rabbitmq:3.8.0